/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ReppuButton {
    }
    interface ReppuSelect {
    }
}
declare global {
    interface HTMLReppuButtonElement extends Components.ReppuButton, HTMLStencilElement {
    }
    var HTMLReppuButtonElement: {
        prototype: HTMLReppuButtonElement;
        new (): HTMLReppuButtonElement;
    };
    interface HTMLReppuSelectElement extends Components.ReppuSelect, HTMLStencilElement {
    }
    var HTMLReppuSelectElement: {
        prototype: HTMLReppuSelectElement;
        new (): HTMLReppuSelectElement;
    };
    interface HTMLElementTagNameMap {
        "reppu-button": HTMLReppuButtonElement;
        "reppu-select": HTMLReppuSelectElement;
    }
}
declare namespace LocalJSX {
    interface ReppuButton {
    }
    interface ReppuSelect {
        "onChange"?: (event: CustomEvent<any>) => void;
    }
    interface IntrinsicElements {
        "reppu-button": ReppuButton;
        "reppu-select": ReppuSelect;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "reppu-button": LocalJSX.ReppuButton & JSXBase.HTMLAttributes<HTMLReppuButtonElement>;
            "reppu-select": LocalJSX.ReppuSelect & JSXBase.HTMLAttributes<HTMLReppuSelectElement>;
        }
    }
}
