/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface BorcButton {
        "enabled": boolean;
        "text": string;
    }
}
declare global {
    interface HTMLBorcButtonElement extends Components.BorcButton, HTMLStencilElement {
    }
    var HTMLBorcButtonElement: {
        prototype: HTMLBorcButtonElement;
        new (): HTMLBorcButtonElement;
    };
    interface HTMLElementTagNameMap {
        "borc-button": HTMLBorcButtonElement;
    }
}
declare namespace LocalJSX {
    interface BorcButton {
        "enabled"?: boolean;
        "onBorcEvent"?: (event: CustomEvent<any>) => void;
        "text"?: string;
    }
    interface IntrinsicElements {
        "borc-button": BorcButton;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "borc-button": LocalJSX.BorcButton & JSXBase.HTMLAttributes<HTMLBorcButtonElement>;
        }
    }
}
